server:
  port: 7789
spring:
  cloud:
    config:
      server:
        git:
          uri: https://git.oschina.net/Lamb7/conf-repo.git
# 对称加密
encrypt:
  key: JOQWUO3198NIU

# client 不需要修改配置，server 会自己解密

# keytool -genkeypair -alias mytestkey -keyalg RSA -dname "CN=Web Server,OU=Unit,O=Organization,L=City,S=State,C=US" -keypass changeme -keystore server.jks -storepass letmein