server:
  port: 7787
spring:
  cloud:
    config:
      server:
        git:
          uri: https://git.oschina.net/Lamb7/conf-repo.git
          # uri: https://git.oschina.net/Lamb7/{application}.git
          # 可以用通配符配置多git仓库（就像是把每个微服务的配置文件各建一个仓库[项目]）
  application:
    name: config-server  # 可同时作为Eureka Client注册

security:
  basic:
    enabled: true
  user:
    name: user
    password: 123

# 五个节点都可以访问，properties 对应 properties， yml 对应 yml

#/{application}/{profile}[/{label}]
#/{application}-{profile}.yml
#/{label}/{application}-{profile}.yml
#/{application}-{profile}.properties
#/{label}/{application}-{profile}.properties
